Ambassador: web.ambassador.core.KernelHandler Class Reference
web.ambassador.core.KernelHandler Class Reference
The KernelHandler class is responsible for handling incoming HTTP requests and returning appropriate responses.
Public Member Functions
void handle (HttpExchange exchange) throws IOException
Handles an incoming HTTP request by parsing the request details, processing the request using the router, and returning an appropriate response.
Static Public Member Functions
static KernelHandler build (Router router, DatabaseManager dbManager, Map< Integer, ErrorController > errorControllers)
Static method to build a new KernelHandler instance.
Protected Member Functions
KernelHandler ()
Private constructor for creating a KernelHandler instance.
Detailed Description
The KernelHandler class is responsible for handling incoming HTTP requests and returning appropriate responses.
This class implements the HttpHandler interface and is part of the server's request handling pipeline. It interacts with the Router, which is used to process the request and determine the correct view/content to return. Additionally, it manages the database connection through the DatabaseManager and handles error responses using the provided ErrorController implementations.
The KernelHandler class is designed to handle various HTTP methods (e.g., GET, POST), parse request headers, cookies, and query parameters, and generate corresponding responses. If an error occurs during request processing, it will handle the error gracefully by using the appropriate error controller.
In the event of an exception or error, a default error handler is used if no specific error controller is provided for the given HTTP status code.
Author
Nathanne Isip <nathanneisip@gmail.com>
Version
1.0
Since
1.0
Definition at line 49 of file KernelHandler.java.
Constructor & Destructor Documentation
KernelHandler()
web.ambassador.core.KernelHandler.KernelHandler () inline protected
Private constructor for creating a KernelHandler instance.
Definition at line 57 of file KernelHandler.java.
Referenced by web.ambassador.core.KernelHandler.build().
Member Function Documentation
build()
static KernelHandler web.ambassador.core.KernelHandler.build (Router router, DatabaseManager dbManager, Map< Integer, ErrorController > errorControllers) inline static
Static method to build a new KernelHandler instance.
This method is used to initialize the handler with the required components such as the Router, DatabaseManager, and error controllers.
Parameters
router The router used for handling requests and determining view/content.
dbManager The database manager used for interacting with the database.
errorControllers A map of error codes to their respective error controllers.
Returns
A KernelHandler instance.
Definition at line 70 of file KernelHandler.java.
References web.ambassador.core.KernelHandler.KernelHandler().
Referenced by web.ambassador.core.Kernel.start().
handle()
void web.ambassador.core.KernelHandler.handle (HttpExchange exchange) throws IOException inline
Handles an incoming HTTP request by parsing the request details, processing the request using the router, and returning an appropriate response.
This method performs the following steps:
Creates a new Request and Response object.
Parses request details such as path, method, headers, cookies, query parameters, and body (for POST requests).
Processes the request using the Router to determine the appropriate view or content.
If the response status code is not 200, an error response is generated using the appropriate error controller.
Writes the response to the HTTP exchange, including headers and response body.
In case of an exception during request processing, the method will respond with a generic 500 Internal Server Error, using the error controller if defined.
Parameters
exchange The HttpExchange object representing the incoming HTTP request and response.
Exceptions
IOException If an I/O error occurs while handling the request or response.
Definition at line 103 of file KernelHandler.java.
References web.ambassador.core.ErrorController.handleError(), and web.ambassador.core.Router.handleRequest().
The documentation for this class was generated from the following file:
src/web/ambassador/core/KernelHandler.java