Ambassador: web.ambassador.core.Route Class Reference
web.ambassador.core.Route Class Reference
The Route class represents an endpoint in a web application, supporting dynamic and static path matching, HTTP method-specific handlers, and parameter extraction from URL paths.
Public Member Functions
Route (String path)
Constructs a Route instance for the specified path.
boolean matches (String path)
Checks if the provided path matches this route.
Map< String, String > extractParams (String path)
Extracts URL parameters from the provided path if the route has dynamic segments.
void addHandler (MethodType type, RouteHandler handler)
Adds an HTTP method-specific handler to the route.
RouteHandler getHandler (MethodType type)
Retrieves the handler for a specific HTTP method.
Detailed Description
The Route class represents an endpoint in a web application, supporting dynamic and static path matching, HTTP method-specific handlers, and parameter extraction from URL paths.
This class can handle paths with dynamic segments (e.g., /user/{id}) or exact paths (e.g., /home). It allows associating handlers with HTTP methods (GET, POST, etc.) for each route.
Author
Nathanne Isip <nathanneisip@gmail.com>
Version
1.0
Since
1.0
Definition at line 39 of file Route.java.
Constructor & Destructor Documentation
Route()
web.ambassador.core.Route.Route (String path) inline
Constructs a Route instance for the specified path.
If the path contains placeholders (e.g., {id}), a dynamic PathPattern is created. Otherwise, the route is treated as an exact match.
Parameters
path The URL path for the route (e.g., /api/items or /user/{id}).
Definition at line 53 of file Route.java.
Member Function Documentation
addHandler()
void web.ambassador.core.Route.addHandler (MethodType type, RouteHandler handler) inline
Adds an HTTP method-specific handler to the route.
Associates a handler with an HTTP method (e.g., GET, POST). This allows different behavior for the same route based on the method used.
Parameters
type The HTTP method (e.g., MethodType.GET).
handler The handler to execute for this method.
Definition at line 108 of file Route.java.
Referenced by web.ambassador.core.Router.registerController().
extractParams()
Map< String, String > web.ambassador.core.Route.extractParams (String path) inline
Extracts URL parameters from the provided path if the route has dynamic segments.
Returns a map of placeholder names and their corresponding values (e.g., {id} -> 42).
Parameters
path The URL path to extract parameters from (e.g., /user/42).
Returns
A map containing parameter names and their values, or an empty map if the path does not have dynamic segments.
Definition at line 93 of file Route.java.
References web.ambassador.core.PathPattern.extractParams().
getHandler()
RouteHandler web.ambassador.core.Route.getHandler (MethodType type) inline
Retrieves the handler for a specific HTTP method.
If no handler is registered for the method, null is returned.
Parameters
type The HTTP method to retrieve the handler for.
Returns
The associated RouteHandler, or null if not found.
Definition at line 119 of file Route.java.
matches()
boolean web.ambassador.core.Route.matches (String path) inline
Checks if the provided path matches this route.
The path is matched against either an exact string or a dynamic pattern depending on how the route was initialized.
Parameters
path The URL path to match (e.g., /user/42).
Returns
true if the path matches the route, false otherwise.
Definition at line 73 of file Route.java.
References web.ambassador.core.PathPattern.matches().
The documentation for this class was generated from the following file:
src/web/ambassador/core/Route.java