Ambassador: web.ambassador.view.Dom Class Reference
web.ambassador.view.Dom Class Reference
Represents an HTML DOM (Document Object Model) element that can be dynamically constructed and rendered as part of an HTTP response.
Public Member Functions
Dom (String tagName)
Constructs a DOM element with the specified tag name.
Dom (String tagName, String textContent)
Constructs a DOM element with a tag name and inner text content.
Dom (String tagName, ViewContent... children)
Constructs a DOM element with a tag name and child elements.
Dom id (String id)
Dom href (String url)
Dom src (String url)
Dom type (String type)
Dom value (String value)
Dom placeholder (String text)
Dom name (String name)
Dom text (String text)
Sets or replaces the inner text content of this element.
Dom attr (String name)
Adds or updates an HTML attribute without a value (e.g., checked, disabled).
Dom attr (String key, String value)
Adds or updates an HTML attribute with a value.
Dom style (String property, String value)
Applies inline CSS styles to the element.
Dom addClass (String... classNames)
Adds CSS classes to the element.
Dom removeClass (String... classNames)
Removes CSS classes from the element.
List< String > getClasses ()
Dom addChild (Dom child)
Dom removeChild (Dom child)
Dom children (ViewContent... elements)
List< ViewContent > getChildren ()
Dom addRow (String... cells)
Dom addHeaderRow (String... headers)
byte[] render ()
Renders the DOM element to a byte array in UTF-8 encoding.
String mimeType ()
Returns the MIME type for HTML content.
String toString ()
Serializes the DOM element and its children to an HTML string.
Static Public Member Functions
static Dom createPage ()
Creates an HTML !DOCTYPE declaration with the root html tag.
static Dom createPage (ViewContent... children)
Creates an HTML !DOCTYPE declaration with child elements nested under the html tag.
static Dom a ()
static Dom a (String link, String text)
static Dom a (String link, String text, String target)
static Dom abbr (String text)
static Dom acronym (String text)
static Dom acronym (String text, String title)
static Dom address (String text)
static Dom address (String text, ViewContent... children)
static Dom area ()
static Dom area (String shape, String coords)
static Dom area (String shape, String coords, String href)
static Dom article ()
static Dom article (ViewContent... children)
static Dom aside ()
static Dom aside (ViewContent... children)
static Dom audio ()
static Dom audio (String src)
static Dom audio (ViewContent... children)
static Dom b ()
static Dom b (String text)
static Dom b (Dom... children)
static Dom base ()
static Dom base (String href)
static Dom base (String href, String target)
static Dom bdi ()
static Dom bdi (String text)
static Dom bdo ()
static Dom bdo (String text)
static Dom bdo (String text, String dir)
static Dom blockquote ()
static Dom blockquote (String cite)
static Dom blockquote (String cite, String text)
static Dom blockquote (String cite, Dom... children)
static Dom body ()
static Dom body (ViewContent... children)
static Dom br ()
static Dom button ()
static Dom button (String text)
static Dom canvas ()
static Dom canvas (String id)
static Dom canvas (String id, int width, int height)
static Dom caption ()
static Dom caption (String align, String text)
static Dom caption (String align, Dom... children)
static Dom div ()
static Dom div (ViewContent... children)
static Dom h1 ()
static Dom h1 (String text)
static Dom h1 (ViewContent... children)
static Dom h2 ()
static Dom h2 (String text)
static Dom h2 (ViewContent... children)
static Dom h3 ()
static Dom h3 (String text)
static Dom h3 (ViewContent... children)
static Dom h4 ()
static Dom h4 (String text)
static Dom h4 (ViewContent... children)
static Dom h5 ()
static Dom h5 (String text)
static Dom h5 (ViewContent... children)
static Dom h6 ()
static Dom h6 (String text)
static Dom h6 (ViewContent... children)
static Dom head ()
static Dom head (ViewContent... children)
static Dom html (String lang)
static Dom html (ViewContent... children)
static Dom html (String lang, ViewContent... children)
static Dom html ()
static Dom noTag (String text)
static Dom p ()
static Dom p (String text)
static Dom p (ViewContent... children)
static Dom script ()
static Dom script (String link)
static Dom script (String lang, String content)
static Dom stylesheet (String path)
static Dom title ()
static Dom title (String text)
static Dom span ()
static Dom input ()
static Dom form ()
static Dom table ()
static Dom tr ()
static Dom td ()
static Dom th ()
static Dom ul ()
static Dom li ()
static Dom img ()
Detailed Description
Represents an HTML DOM (Document Object Model) element that can be dynamically constructed and rendered as part of an HTTP response.
The Dom class implements the ViewContent interface, allowing HTML elements to be programmatically generated, modified, and serialized into an HTML string. This class provides a flexible and fluent API to build complex HTML structures without manually writing raw HTML tags.
Common use cases for this class include:
Generating HTML tables, forms, and component-based UIs.
Creating dynamic server-rendered HTML pages.
Embedding HTML fragments in responses for web applications.
The Dom class supports the addition of children, attributes, CSS classes, inline styles, and custom HTML content. Cached rendering optimizes performance by storing the serialized byte array of the generated HTML.
See also
web.ambassador.view.ViewContent
Author
Nathanne Isip <nathanneisip@gmail.com>
Since
1.0
Version
1.0
Definition at line 52 of file Dom.java.
Constructor & Destructor Documentation
Dom() [1/3]
web.ambassador.view.Dom.Dom (String tagName) inline
Constructs a DOM element with the specified tag name.
Parameters
tagName The HTML tag name (e.g., "div", "span").
Definition at line 66 of file Dom.java.
Dom() [2/3]
web.ambassador.view.Dom.Dom (String tagName, String textContent) inline
Constructs a DOM element with a tag name and inner text content.
Parameters
tagName The HTML tag name.
textContent The inner text content of the element.
Definition at line 80 of file Dom.java.
Dom() [3/3]
web.ambassador.view.Dom.Dom (String tagName, ViewContent... children) inline
Constructs a DOM element with a tag name and child elements.
Parameters
tagName The HTML tag name.
children Child elements to be nested within this element.
Definition at line 91 of file Dom.java.
Member Function Documentation
a() [1/3]
static Dom web.ambassador.view.Dom.a () inline static
Definition at line 119 of file Dom.java.
a() [2/3]
static Dom web.ambassador.view.Dom.a (String link, String text) inline static
Definition at line 123 of file Dom.java.
References web.ambassador.view.Dom.href(), and web.ambassador.view.Dom.text().
a() [3/3]
static Dom web.ambassador.view.Dom.a (String link, String text, String target) inline static
Definition at line 128 of file Dom.java.
References web.ambassador.view.Dom.attr(), web.ambassador.view.Dom.href(), and web.ambassador.view.Dom.text().
abbr()
static Dom web.ambassador.view.Dom.abbr (String text) inline static
Definition at line 134 of file Dom.java.
References web.ambassador.view.Dom.text().
acronym() [1/2]
static Dom web.ambassador.view.Dom.acronym (String text) inline static
Definition at line 138 of file Dom.java.
References web.ambassador.view.Dom.text().
acronym() [2/2]
static Dom web.ambassador.view.Dom.acronym (String text, String title) inline static
Definition at line 142 of file Dom.java.
References web.ambassador.view.Dom.attr(), web.ambassador.view.Dom.text(), and web.ambassador.view.Dom.title().
addChild()
Dom web.ambassador.view.Dom.addChild (Dom child) inline
Definition at line 578 of file Dom.java.
Referenced by web.ambassador.view.Dom.addHeaderRow(), and web.ambassador.view.Dom.addRow().
addClass()
Dom web.ambassador.view.Dom.addClass (String... classNames) inline
Adds CSS classes to the element.
Parameters
classNames CSS class names to add.
Returns
This Dom instance.
Definition at line 558 of file Dom.java.
addHeaderRow()
Dom web.ambassador.view.Dom.addHeaderRow (String... headers) inline
Definition at line 605 of file Dom.java.
References web.ambassador.view.Dom.addChild(), web.ambassador.view.Dom.text(), web.ambassador.view.Dom.th(), and web.ambassador.view.Dom.tr().
address() [1/2]
static Dom web.ambassador.view.Dom.address (String text) inline static
Definition at line 147 of file Dom.java.
References web.ambassador.view.Dom.text().
address() [2/2]
static Dom web.ambassador.view.Dom.address (String text, ViewContent... children) inline static
Definition at line 151 of file Dom.java.
References web.ambassador.view.Dom.text().
addRow()
Dom web.ambassador.view.Dom.addRow (String... cells) inline
Definition at line 597 of file Dom.java.
References web.ambassador.view.Dom.addChild(), web.ambassador.view.Dom.td(), web.ambassador.view.Dom.text(), and web.ambassador.view.Dom.tr().
area() [1/3]
static Dom web.ambassador.view.Dom.area () inline static
Definition at line 156 of file Dom.java.
area() [2/3]
static Dom web.ambassador.view.Dom.area (String shape, String coords) inline static
Definition at line 160 of file Dom.java.
References web.ambassador.view.Dom.attr().
area() [3/3]
static Dom web.ambassador.view.Dom.area (String shape, String coords, String href) inline static
Definition at line 166 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.href().
article() [1/2]
static Dom web.ambassador.view.Dom.article () inline static
Definition at line 173 of file Dom.java.
article() [2/2]
static Dom web.ambassador.view.Dom.article (ViewContent... children) inline static
Definition at line 177 of file Dom.java.
aside() [1/2]
static Dom web.ambassador.view.Dom.aside () inline static
Definition at line 182 of file Dom.java.
aside() [2/2]
static Dom web.ambassador.view.Dom.aside (ViewContent... children) inline static
Definition at line 186 of file Dom.java.
attr() [1/2]
Dom web.ambassador.view.Dom.attr (String key, String value) inline
Adds or updates an HTML attribute with a value.
Parameters
key The attribute name.
value The attribute value.
Returns
This Dom instance.
Definition at line 535 of file Dom.java.
References web.ambassador.view.Dom.value().
attr() [2/2]
Dom web.ambassador.view.Dom.attr (String name) inline
Adds or updates an HTML attribute without a value (e.g., checked, disabled).
Parameters
name The name of the attribute.
Returns
This Dom instance.
Definition at line 523 of file Dom.java.
References web.ambassador.view.Dom.name().
Referenced by web.ambassador.view.Dom.a(), web.ambassador.view.Dom.acronym(), web.ambassador.view.Dom.area(), web.ambassador.view.Dom.area(), web.ambassador.view.Dom.audio(), web.ambassador.view.Dom.base(), web.ambassador.view.Dom.bdo(), web.ambassador.view.Dom.blockquote(), web.ambassador.view.Dom.blockquote(), web.ambassador.view.Dom.canvas(), web.ambassador.view.Dom.caption(), web.ambassador.view.Dom.createPage(), web.ambassador.view.Dom.createPage(), web.ambassador.view.Dom.href(), web.ambassador.view.Dom.html(), web.ambassador.view.Dom.html(), web.ambassador.view.Dom.id(), web.ambassador.view.Dom.name(), web.ambassador.view.Dom.placeholder(), web.ambassador.view.Dom.script(), web.ambassador.view.Dom.script(), web.ambassador.view.Dom.src(), web.ambassador.view.Dom.stylesheet(), web.ambassador.view.Dom.type(), and web.ambassador.view.Dom.value().
audio() [1/3]
static Dom web.ambassador.view.Dom.audio () inline static
Definition at line 191 of file Dom.java.
audio() [2/3]
static Dom web.ambassador.view.Dom.audio (String src) inline static
Definition at line 195 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.src().
audio() [3/3]
static Dom web.ambassador.view.Dom.audio (ViewContent... children) inline static
Definition at line 200 of file Dom.java.
b() [1/3]
static Dom web.ambassador.view.Dom.b () inline static
Definition at line 205 of file Dom.java.
b() [2/3]
static Dom web.ambassador.view.Dom.b (Dom... children) inline static
Definition at line 213 of file Dom.java.
b() [3/3]
static Dom web.ambassador.view.Dom.b (String text) inline static
Definition at line 209 of file Dom.java.
References web.ambassador.view.Dom.text().
base() [1/3]
static Dom web.ambassador.view.Dom.base () inline static
Definition at line 218 of file Dom.java.
base() [2/3]
static Dom web.ambassador.view.Dom.base (String href) inline static
Definition at line 222 of file Dom.java.
References web.ambassador.view.Dom.href().
base() [3/3]
static Dom web.ambassador.view.Dom.base (String href, String target) inline static
Definition at line 227 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.href().
bdi() [1/2]
static Dom web.ambassador.view.Dom.bdi () inline static
Definition at line 233 of file Dom.java.
bdi() [2/2]
static Dom web.ambassador.view.Dom.bdi (String text) inline static
Definition at line 237 of file Dom.java.
References web.ambassador.view.Dom.text().
bdo() [1/3]
static Dom web.ambassador.view.Dom.bdo () inline static
Definition at line 241 of file Dom.java.
bdo() [2/3]
static Dom web.ambassador.view.Dom.bdo (String text) inline static
Definition at line 245 of file Dom.java.
References web.ambassador.view.Dom.text().
bdo() [3/3]
static Dom web.ambassador.view.Dom.bdo (String text, String dir) inline static
Definition at line 249 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.text().
blockquote() [1/4]
static Dom web.ambassador.view.Dom.blockquote () inline static
Definition at line 254 of file Dom.java.
blockquote() [2/4]
static Dom web.ambassador.view.Dom.blockquote (String cite) inline static
Definition at line 258 of file Dom.java.
References web.ambassador.view.Dom.attr().
blockquote() [3/4]
static Dom web.ambassador.view.Dom.blockquote (String cite, Dom... children) inline static
Definition at line 268 of file Dom.java.
blockquote() [4/4]
static Dom web.ambassador.view.Dom.blockquote (String cite, String text) inline static
Definition at line 263 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.text().
body() [1/2]
static Dom web.ambassador.view.Dom.body () inline static
Definition at line 274 of file Dom.java.
body() [2/2]
static Dom web.ambassador.view.Dom.body (ViewContent... children) inline static
Definition at line 278 of file Dom.java.
br()
static Dom web.ambassador.view.Dom.br () inline static
Definition at line 283 of file Dom.java.
button() [1/2]
static Dom web.ambassador.view.Dom.button () inline static
Definition at line 287 of file Dom.java.
button() [2/2]
static Dom web.ambassador.view.Dom.button (String text) inline static
Definition at line 291 of file Dom.java.
References web.ambassador.view.Dom.text().
canvas() [1/3]
static Dom web.ambassador.view.Dom.canvas () inline static
Definition at line 295 of file Dom.java.
canvas() [2/3]
static Dom web.ambassador.view.Dom.canvas (String id) inline static
Definition at line 299 of file Dom.java.
References web.ambassador.view.Dom.id().
canvas() [3/3]
static Dom web.ambassador.view.Dom.canvas (String id, int width, int height) inline static
Definition at line 304 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.id().
caption() [1/3]
static Dom web.ambassador.view.Dom.caption () inline static
Definition at line 311 of file Dom.java.
caption() [2/3]
static Dom web.ambassador.view.Dom.caption (String align, Dom... children) inline static
Definition at line 320 of file Dom.java.
caption() [3/3]
static Dom web.ambassador.view.Dom.caption (String align, String text) inline static
Definition at line 315 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.text().
children()
Dom web.ambassador.view.Dom.children (ViewContent... elements) inline
Definition at line 588 of file Dom.java.
createPage() [1/2]
static Dom web.ambassador.view.Dom.createPage () inline static
Creates an HTML !DOCTYPE declaration with the root html tag.
Returns
A Dom object representing an HTML page structure.
Definition at line 101 of file Dom.java.
References web.ambassador.view.Dom.attr().
createPage() [2/2]
static Dom web.ambassador.view.Dom.createPage (ViewContent... children) inline static
Creates an HTML !DOCTYPE declaration with child elements nested under the html tag.
Parameters
children Child elements to be added to the HTML page.
Returns
A Dom object representing an HTML page structure.
Definition at line 113 of file Dom.java.
References web.ambassador.view.Dom.attr().
div() [1/2]
static Dom web.ambassador.view.Dom.div () inline static
Definition at line 326 of file Dom.java.
div() [2/2]
static Dom web.ambassador.view.Dom.div (ViewContent... children) inline static
Definition at line 330 of file Dom.java.
form()
static Dom web.ambassador.view.Dom.form () inline static
Definition at line 489 of file Dom.java.
getChildren()
List< ViewContent > web.ambassador.view.Dom.getChildren () inline
Definition at line 593 of file Dom.java.
getClasses()
List< String > web.ambassador.view.Dom.getClasses () inline
Definition at line 574 of file Dom.java.
h1() [1/3]
static Dom web.ambassador.view.Dom.h1 () inline static
Definition at line 335 of file Dom.java.
h1() [2/3]
static Dom web.ambassador.view.Dom.h1 (String text) inline static
Definition at line 339 of file Dom.java.
References web.ambassador.view.Dom.text().
h1() [3/3]
static Dom web.ambassador.view.Dom.h1 (ViewContent... children) inline static
Definition at line 343 of file Dom.java.
h2() [1/3]
static Dom web.ambassador.view.Dom.h2 () inline static
Definition at line 348 of file Dom.java.
h2() [2/3]
static Dom web.ambassador.view.Dom.h2 (String text) inline static
Definition at line 352 of file Dom.java.
References web.ambassador.view.Dom.text().
h2() [3/3]
static Dom web.ambassador.view.Dom.h2 (ViewContent... children) inline static
Definition at line 356 of file Dom.java.
h3() [1/3]
static Dom web.ambassador.view.Dom.h3 () inline static
Definition at line 361 of file Dom.java.
h3() [2/3]
static Dom web.ambassador.view.Dom.h3 (String text) inline static
Definition at line 365 of file Dom.java.
References web.ambassador.view.Dom.text().
h3() [3/3]
static Dom web.ambassador.view.Dom.h3 (ViewContent... children) inline static
Definition at line 369 of file Dom.java.
h4() [1/3]
static Dom web.ambassador.view.Dom.h4 () inline static
Definition at line 374 of file Dom.java.
h4() [2/3]
static Dom web.ambassador.view.Dom.h4 (String text) inline static
Definition at line 378 of file Dom.java.
References web.ambassador.view.Dom.text().
h4() [3/3]
static Dom web.ambassador.view.Dom.h4 (ViewContent... children) inline static
Definition at line 382 of file Dom.java.
h5() [1/3]
static Dom web.ambassador.view.Dom.h5 () inline static
Definition at line 387 of file Dom.java.
h5() [2/3]
static Dom web.ambassador.view.Dom.h5 (String text) inline static
Definition at line 391 of file Dom.java.
References web.ambassador.view.Dom.text().
h5() [3/3]
static Dom web.ambassador.view.Dom.h5 (ViewContent... children) inline static
Definition at line 395 of file Dom.java.
h6() [1/3]
static Dom web.ambassador.view.Dom.h6 () inline static
Definition at line 400 of file Dom.java.
h6() [2/3]
static Dom web.ambassador.view.Dom.h6 (String text) inline static
Definition at line 404 of file Dom.java.
References web.ambassador.view.Dom.text().
h6() [3/3]
static Dom web.ambassador.view.Dom.h6 (ViewContent... children) inline static
Definition at line 408 of file Dom.java.
head() [1/2]
static Dom web.ambassador.view.Dom.head () inline static
Definition at line 413 of file Dom.java.
head() [2/2]
static Dom web.ambassador.view.Dom.head (ViewContent... children) inline static
Definition at line 417 of file Dom.java.
href()
Dom web.ambassador.view.Dom.href (String url) inline
Definition at line 499 of file Dom.java.
References web.ambassador.view.Dom.attr().
Referenced by web.ambassador.view.Dom.a(), web.ambassador.view.Dom.a(), web.ambassador.view.Dom.area(), web.ambassador.view.Dom.base(), web.ambassador.view.Dom.base(), and web.ambassador.view.Dom.stylesheet().
html() [1/4]
static Dom web.ambassador.view.Dom.html () inline static
Definition at line 436 of file Dom.java.
Referenced by web.ambassador.view.Dom.toString().
html() [2/4]
static Dom web.ambassador.view.Dom.html (String lang) inline static
Definition at line 422 of file Dom.java.
References web.ambassador.view.Dom.attr().
html() [3/4]
static Dom web.ambassador.view.Dom.html (String lang, ViewContent... children) inline static
Definition at line 431 of file Dom.java.
References web.ambassador.view.Dom.attr().
html() [4/4]
static Dom web.ambassador.view.Dom.html (ViewContent... children) inline static
Definition at line 427 of file Dom.java.
id()
Dom web.ambassador.view.Dom.id (String id) inline
Definition at line 498 of file Dom.java.
References web.ambassador.view.Dom.attr().
Referenced by web.ambassador.view.Dom.canvas(), and web.ambassador.view.Dom.canvas().
img()
static Dom web.ambassador.view.Dom.img () inline static
Definition at line 496 of file Dom.java.
input()
static Dom web.ambassador.view.Dom.input () inline static
Definition at line 488 of file Dom.java.
li()
static Dom web.ambassador.view.Dom.li () inline static
Definition at line 495 of file Dom.java.
mimeType()
String web.ambassador.view.Dom.mimeType () inline
Returns the MIME type for HTML content.
Returns
"text/html".
Implements web.ambassador.view.ViewContent.
Definition at line 635 of file Dom.java.
name()
Dom web.ambassador.view.Dom.name (String name) inline
Definition at line 504 of file Dom.java.
References web.ambassador.view.Dom.attr().
Referenced by web.ambassador.view.Dom.attr().
noTag()
static Dom web.ambassador.view.Dom.noTag (String text) inline static
Definition at line 440 of file Dom.java.
References web.ambassador.view.Dom.text().
p() [1/3]
static Dom web.ambassador.view.Dom.p () inline static
Definition at line 445 of file Dom.java.
p() [2/3]
static Dom web.ambassador.view.Dom.p (String text) inline static
Definition at line 449 of file Dom.java.
References web.ambassador.view.Dom.text().
p() [3/3]
static Dom web.ambassador.view.Dom.p (ViewContent... children) inline static
Definition at line 453 of file Dom.java.
placeholder()
Dom web.ambassador.view.Dom.placeholder (String text) inline
Definition at line 503 of file Dom.java.
References web.ambassador.view.Dom.attr().
removeChild()
Dom web.ambassador.view.Dom.removeChild (Dom child) inline
Definition at line 583 of file Dom.java.
removeClass()
Dom web.ambassador.view.Dom.removeClass (String... classNames) inline
Removes CSS classes from the element.
Parameters
classNames CSS class names to remove.
Returns
This Dom instance.
Definition at line 569 of file Dom.java.
render()
byte[] web.ambassador.view.Dom.render () inline
Renders the DOM element to a byte array in UTF-8 encoding.
The resulting byte array is cached for reuse to optimize performance.
Returns
A byte array representing the serialized HTML of this element.
Implements web.ambassador.view.ViewContent.
Definition at line 621 of file Dom.java.
References web.ambassador.view.Dom.toString().
script() [1/3]
static Dom web.ambassador.view.Dom.script () inline static
Definition at line 458 of file Dom.java.
script() [2/3]
static Dom web.ambassador.view.Dom.script (String lang, String content) inline static
Definition at line 467 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.text().
script() [3/3]
static Dom web.ambassador.view.Dom.script (String link) inline static
Definition at line 462 of file Dom.java.
References web.ambassador.view.Dom.attr().
span()
static Dom web.ambassador.view.Dom.span () inline static
Definition at line 487 of file Dom.java.
src()
Dom web.ambassador.view.Dom.src (String url) inline
Definition at line 500 of file Dom.java.
References web.ambassador.view.Dom.attr().
Referenced by web.ambassador.view.Dom.audio().
style()
Dom web.ambassador.view.Dom.style (String property, String value) inline
Applies inline CSS styles to the element.
Parameters
property The CSS property (e.g., color).
value The value of the CSS property (e.g., red).
Returns
This Dom instance.
Definition at line 547 of file Dom.java.
References web.ambassador.view.Dom.value().
stylesheet()
static Dom web.ambassador.view.Dom.stylesheet (String path) inline static
Definition at line 473 of file Dom.java.
References web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.href().
table()
static Dom web.ambassador.view.Dom.table () inline static
Definition at line 490 of file Dom.java.
td()
static Dom web.ambassador.view.Dom.td () inline static
Definition at line 492 of file Dom.java.
Referenced by web.ambassador.view.Dom.addRow().
text()
Dom web.ambassador.view.Dom.text (String text) inline
Sets or replaces the inner text content of this element.
Parameters
text The new text content.
Returns
This Dom instance, for method chaining.
Definition at line 512 of file Dom.java.
References web.ambassador.view.Dom.text().
Referenced by web.ambassador.view.Dom.a(), web.ambassador.view.Dom.a(), web.ambassador.view.Dom.abbr(), web.ambassador.view.Dom.acronym(), web.ambassador.view.Dom.acronym(), web.ambassador.view.Dom.addHeaderRow(), web.ambassador.view.Dom.address(), web.ambassador.view.Dom.address(), web.ambassador.view.Dom.addRow(), web.ambassador.view.Dom.b(), web.ambassador.view.Dom.bdi(), web.ambassador.view.Dom.bdo(), web.ambassador.view.Dom.bdo(), web.ambassador.view.Dom.blockquote(), web.ambassador.view.Dom.button(), web.ambassador.view.Dom.caption(), web.ambassador.view.Dom.h1(), web.ambassador.view.Dom.h2(), web.ambassador.view.Dom.h3(), web.ambassador.view.Dom.h4(), web.ambassador.view.Dom.h5(), web.ambassador.view.Dom.h6(), web.ambassador.view.Dom.noTag(), web.ambassador.view.Dom.p(), web.ambassador.view.Dom.script(), web.ambassador.view.Dom.text(), and web.ambassador.view.Dom.title().
th()
static Dom web.ambassador.view.Dom.th () inline static
Definition at line 493 of file Dom.java.
Referenced by web.ambassador.view.Dom.addHeaderRow().
title() [1/2]
static Dom web.ambassador.view.Dom.title () inline static
Definition at line 479 of file Dom.java.
Referenced by web.ambassador.view.Dom.acronym().
title() [2/2]
static Dom web.ambassador.view.Dom.title (String text) inline static
Definition at line 483 of file Dom.java.
References web.ambassador.view.Dom.text().
toString()
String web.ambassador.view.Dom.toString () inline
Serializes the DOM element and its children to an HTML string.
Returns
A string representing the HTML structure of this element.
Definition at line 645 of file Dom.java.
References web.ambassador.view.Dom.html(), and web.ambassador.view.Dom.toString().
Referenced by web.ambassador.view.Dom.render(), and web.ambassador.view.Dom.toString().
tr()
static Dom web.ambassador.view.Dom.tr () inline static
Definition at line 491 of file Dom.java.
Referenced by web.ambassador.view.Dom.addHeaderRow(), and web.ambassador.view.Dom.addRow().
type()
Dom web.ambassador.view.Dom.type (String type) inline
Definition at line 501 of file Dom.java.
References web.ambassador.view.Dom.attr().
ul()
static Dom web.ambassador.view.Dom.ul () inline static
Definition at line 494 of file Dom.java.
value()
Dom web.ambassador.view.Dom.value (String value) inline
Definition at line 502 of file Dom.java.
References web.ambassador.view.Dom.attr().
Referenced by web.ambassador.view.Dom.attr(), and web.ambassador.view.Dom.style().
The documentation for this class was generated from the following file:
src/web/ambassador/view/Dom.java