Ambassador: web.ambassador.core.Router Class Reference
web.ambassador.core.Router Class Reference
The Router class handles the registration of controller classes and maps incoming HTTP requests to the appropriate route handlers.
Public Member Functions
Router ()
Constructs a new Router instance with an empty list of routes and an asset handler for serving static files.
void registerController (Class<?> controllerClass)
Registers a controller class and extracts route mappings from its annotated methods.
ViewContent handleRequest (Request request, Response response, DatabaseManager dbManager)
Handles incoming HTTP requests by matching the request path to a registered route.
Detailed Description
The Router class handles the registration of controller classes and maps incoming HTTP requests to the appropriate route handlers.
It acts as the entry point for processing web requests in the application.
The Router supports dynamic registration of routes through controller annotations, enabling flexible and scalable request handling.
Key Responsibilities:
Register controller classes and associate routes dynamically.
Route incoming requests to the correct handler based on path and method.
Handle static asset requests (e.g., CSS, JS, images) through an AssetHandler.
Return appropriate HTTP responses (404, 405) for unmatched or invalid requests.
Author
Nathanne Isip <nathanneisip@gmail.com>
Version
1.0
Since
1.0
Definition at line 53 of file Router.java.
Constructor & Destructor Documentation
Router()
web.ambassador.core.Router.Router () inline
Constructs a new Router instance with an empty list of routes and an asset handler for serving static files.
Definition at line 61 of file Router.java.
Member Function Documentation
handleRequest()
ViewContent web.ambassador.core.Router.handleRequest (Request request, Response response, DatabaseManager dbManager) inline
Handles incoming HTTP requests by matching the request path to a registered route.
If the request path starts with /assets/, the request is forwarded to the AssetHandler to retrieve static assets.
For other paths, the router attempts to find a matching route and invokes the associated route handler. If no match is found, a 404 response is returned. If the method is not allowed, a 405 response is generated.
Parameters
request The incoming HTTP request.
response The HTTP response to populate.
dbManager The database manager to provide access to data.
Returns
A ViewContent representing the response body (HTML, JSON, etc.).
Definition at line 111 of file Router.java.
References web.ambassador.core.AssetHandler.getAsset(), web.ambassador.core.AssetResponse.getMimeType(), web.ambassador.core.RouteHandler.handle(), and web.ambassador.core.AssetResponse.wasFound().
Referenced by web.ambassador.core.KernelHandler.handle().
registerController()
void web.ambassador.core.Router.registerController (Class<?> controllerClass) inline
Registers a controller class and extracts route mappings from its annotated methods.
This method scans the provided controller class for @Method annotations and registers the corresponding routes dynamically. The base path is extracted from the @Controller annotation.
Parameters
controllerClass The controller class to register.
Definition at line 76 of file Router.java.
References web.ambassador.core.Route.addHandler(), and web.ambassador.annotations.Method.value().
Referenced by web.ambassador.core.Kernel.registerController().
The documentation for this class was generated from the following file:
src/web/ambassador/core/Router.java