Ambassador: web.ambassador.core.Kernel Class Reference
web.ambassador.core.Kernel Class Reference
Primary orchestrator for HTTP server management, routing, and database connection pooling.
Public Member Functions
Kernel (int port)
Constructs a basic Kernel instance with a specified port and default configuration.
Kernel (int poolSize, int backlog, int port, String url, String username, String password)
Constructs a Kernel with database connectivity and custom connection pooling.
Kernel (KernelConfig config)
Constructs a Kernel instance using a pre-defined configuration object.
void setupShutdownHook (Runnable onSuccess, Runnable onFail)
Registers shutdown hooks to ensure clean server termination.
void setMaxThreads (int threads)
Sets the maximum number of threads for the thread pool.
void setErrorController (int statusCode, ErrorController controller)
Registers custom error controllers for handling specific HTTP errors.
void registerController (Class<?> controllerClass)
Registers a controller class with the router for handling HTTP requests.
void start () throws IOException
Starts the HTTP server and initializes the request processing pipeline.
void stop ()
Stops the HTTP server and shuts down associated resources gracefully.
void close ()
Closes the Kernel and performs resource cleanup.
Detailed Description
Primary orchestrator for HTTP server management, routing, and database connection pooling.
The Kernel class encapsulates the core logic of starting and managing an HTTP server using Java's built-in HttpServer class. It handles request routing, manages thread pools for request execution, and facilitates interaction with the database layer via the DatabaseManager.
Key features include:
Configurable thread pool management
Dynamic controller registration for routing
Graceful shutdown with automatic resource cleanup
Customizable error handling for HTTP responses
Database connection pooling and management
Author
Nathanne Isip <nathanneisip@gmail.com>
Version
1.0
Since
1.0
Definition at line 49 of file Kernel.java.
Constructor & Destructor Documentation
Kernel() [1/3]
web.ambassador.core.Kernel.Kernel (int port) inline
Constructs a basic Kernel instance with a specified port and default configuration.
This constructor sets up an HTTP server with minimal configuration. No database connections are initialized in this mode.
Parameters
port The port on which the server will run.
Definition at line 98 of file Kernel.java.
Kernel() [2/3]
web.ambassador.core.Kernel.Kernel (int poolSize, int backlog, int port, String url, String username, String password) inline
Constructs a Kernel with database connectivity and custom connection pooling.
This constructor initializes the web server with database integration, allowing efficient connection pooling.
Parameters
poolSize Size of the database connection pool.
backlog Maximum backlog of incoming connections.
port Server port for listening.
url Database connection URL.
username Database username.
password Database password.
Definition at line 120 of file Kernel.java.
Kernel() [3/3]
web.ambassador.core.Kernel.Kernel (KernelConfig config) inline
Constructs a Kernel instance using a pre-defined configuration object.
This allows flexible initialization by passing a KernelConfig object, which encapsulates various server and database configuration parameters.
Parameters
config KernelConfig object containing server and database configuration.
Definition at line 145 of file Kernel.java.
Member Function Documentation
close()
void web.ambassador.core.Kernel.close () inline
Closes the Kernel and performs resource cleanup.
This method is part of the AutoCloseable interface, ensuring that resources are cleaned up properly when the Kernel instance is closed. It triggers any registered success or failure cleanup actions through the Cleaner API.
Example:
try (Kernel kernel = new Kernel(8080)) {
    kernel.start();
} // Kernel will be automatically closed here
Definition at line 316 of file Kernel.java.
registerController()
void web.ambassador.core.Kernel.registerController (Class<?> controllerClass) inline
Registers a controller class with the router for handling HTTP requests.
This method dynamically registers a controller class, which contains request-handling methods mapped to specific routes. The controller must follow the expected structure to be properly recognized by the router.
Parameters
controllerClass Class object representing the controller to be registered.
Example:
kernel.registerController(MyController.class);
Definition at line 219 of file Kernel.java.
References web.ambassador.core.Router.registerController().
setErrorController()
void web.ambassador.core.Kernel.setErrorController (int statusCode, ErrorController controller) inline
Registers custom error controllers for handling specific HTTP errors.
Parameters
statusCode HTTP status code (e.g., 404, 500).
controller ErrorController to handle the error.
Definition at line 201 of file Kernel.java.
setMaxThreads()
void web.ambassador.core.Kernel.setMaxThreads (int threads) inline
Sets the maximum number of threads for the thread pool.
Parameters
threads Maximum number of threads.
Definition at line 191 of file Kernel.java.
setupShutdownHook()
void web.ambassador.core.Kernel.setupShutdownHook (Runnable onSuccess, Runnable onFail) inline
Registers shutdown hooks to ensure clean server termination.
Parameters
onSuccess Runnable to execute upon successful shutdown.
onFail Runnable to execute if shutdown encounters an error.
Definition at line 171 of file Kernel.java.
References web.ambassador.core.Kernel.stop().
start()
void web.ambassador.core.Kernel.start () throws IOException inline
Starts the HTTP server and initializes the request processing pipeline.
This method sets up the HTTP server to listen on the specified port, creates a thread pool for handling incoming requests, and registers the root request handler (KernelHandler) to manage routing and error handling.
The server operates asynchronously, processing multiple requests concurrently based on the configured thread pool size.
Exceptions
IOException if the server fails to start or encounters binding issues.
Example:
kernel.start();
Definition at line 240 of file Kernel.java.
References web.ambassador.core.KernelHandler.build().
stop()
void web.ambassador.core.Kernel.stop () inline
Stops the HTTP server and shuts down associated resources gracefully.
This method initiates the shutdown of the thread pool and closes all active database connections. It ensures that ongoing tasks are completed within a specified timeout period (60 seconds). If tasks do not terminate within this period, a forceful shutdown is triggered.
This method is invoked automatically during shutdown or can be called explicitly.
Example:
kernel.stop();
Definition at line 283 of file Kernel.java.
Referenced by web.ambassador.core.Kernel.setupShutdownHook().
The documentation for this class was generated from the following file:
src/web/ambassador/core/Kernel.java