Ambassador: web.ambassador.db.QueryBuilder Class Reference
web.ambassador.db.QueryBuilder Class Reference
A utility class for dynamically constructing SQL queries with support for the most common SQL clauses.
Public Member Functions
QueryBuilder ()
Constructs a new empty QueryBuilder instance.
QueryBuilder select (String... columns)
Adds a SELECT clause to the SQL query.
QueryBuilder from (String table)
Adds a FROM clause to the SQL query to specify the table to query data from.
QueryBuilder where (String condition)
Adds a WHERE clause to the SQL query with the specified condition.
QueryBuilder and (String condition)
Adds an AND condition to the WHERE clause of the SQL query.
QueryBuilder or (String condition)
Adds an OR condition to the WHERE clause of the SQL query.
QueryBuilder orderBy (String... columns)
Adds an ORDER BY clause to the SQL query to specify sorting columns.
QueryBuilder limit (int limit)
Adds a LIMIT clause to the SQL query to limit the number of rows returned.
QueryBuilder offset (int offset)
Adds an OFFSET clause to the SQL query to skip a number of rows before returning results.
QueryBuilder addParameter (Object value)
Adds a parameter to the query.
PreparedStatement prepare (Connection connection) throws SQLException
Prepares a PreparedStatement for execution using the current query and parameters.
Detailed Description
A utility class for dynamically constructing SQL queries with support for the most common SQL clauses.
This class provides a fluent API to help developers build SQL queries by appending various parts of the query such as SELECT, FROM, WHERE, AND, OR, ORDER BY, LIMIT, and OFFSET. Additionally, it allows for adding parameters to the query for safe execution using a PreparedStatement. The class handles the correct formatting of SQL syntax and supports dynamic query building in a flexible manner.
Example usage:
QueryBuilder queryBuilder = new QueryBuilder();
PreparedStatement query = queryBuilder.select("name", "age")
    .from("users")
    .where("age > ?")
    .orderBy("name")
    .limit(10)
    .offset(0)
    .addParameter(25)
    .prepare(connection);
This class is useful for constructing queries dynamically based on different conditions, and it abstracts away the manual creation and formatting of SQL queries.
Author
Nathanne Isip <nathanneisip@gmail.com>
Version
1.0
Since
1.0
See also
web.ambassador.db.DatabaseManager
web.ambassador.db.RowMapper
web.ambassador.db.TransactionCallback
Definition at line 57 of file QueryBuilder.java.
Constructor & Destructor Documentation
QueryBuilder()
web.ambassador.db.QueryBuilder.QueryBuilder () inline
Constructs a new empty QueryBuilder instance.
Initializes an empty query string and an empty list of parameters. This constructor is used to start building a SQL query using the fluent API.
Definition at line 68 of file QueryBuilder.java.
Member Function Documentation
addParameter()
QueryBuilder web.ambassador.db.QueryBuilder.addParameter (Object value) inline
Adds a parameter to the query.
This method is used to safely bind values to the SQL query (e.g., to avoid SQL injection attacks).
Parameters
value The value of the parameter to be added to the query.
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 174 of file QueryBuilder.java.
and()
QueryBuilder web.ambassador.db.QueryBuilder.and (String condition) inline
Adds an AND condition to the WHERE clause of the SQL query.
Parameters
condition The condition to be appended with the AND keyword (e.g., "salary < 50000").
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 118 of file QueryBuilder.java.
from()
QueryBuilder web.ambassador.db.QueryBuilder.from (String table) inline
Adds a FROM clause to the SQL query to specify the table to query data from.
Parameters
table The name of the table to select data from.
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 96 of file QueryBuilder.java.
limit()
QueryBuilder web.ambassador.db.QueryBuilder.limit (int limit) inline
Adds a LIMIT clause to the SQL query to limit the number of rows returned.
Parameters
limit The maximum number of rows to return.
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 151 of file QueryBuilder.java.
References web.ambassador.db.QueryBuilder.limit().
Referenced by web.ambassador.db.QueryBuilder.limit().
offset()
QueryBuilder web.ambassador.db.QueryBuilder.offset (int offset) inline
Adds an OFFSET clause to the SQL query to skip a number of rows before returning results.
Parameters
offset The number of rows to skip.
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 162 of file QueryBuilder.java.
References web.ambassador.db.QueryBuilder.offset().
Referenced by web.ambassador.db.QueryBuilder.offset().
or()
QueryBuilder web.ambassador.db.QueryBuilder.or (String condition) inline
Adds an OR condition to the WHERE clause of the SQL query.
Parameters
condition The condition to be appended with the OR keyword (e.g., "city = 'New York'").
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 129 of file QueryBuilder.java.
orderBy()
QueryBuilder web.ambassador.db.QueryBuilder.orderBy (String... columns) inline
Adds an ORDER BY clause to the SQL query to specify sorting columns.
Parameters
columns The columns to order by, separated by commas.
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 140 of file QueryBuilder.java.
prepare()
PreparedStatement web.ambassador.db.QueryBuilder.prepare (Connection connection) throws SQLException inline
Prepares a PreparedStatement for execution using the current query and parameters.
This method takes a Connection and creates a PreparedStatement with the built query string and binds all the parameters that have been added using addParameter(Object).
Parameters
connection The Connection to use for preparing the statement.
Returns
A PreparedStatement ready for execution.
Exceptions
SQLException If there is an error while preparing the statement or setting the parameters.
Definition at line 189 of file QueryBuilder.java.
select()
QueryBuilder web.ambassador.db.QueryBuilder.select (String... columns) inline
Adds a SELECT clause to the SQL query.
If no columns are specified, "*" is used to select all columns. Otherwise, the provided column names are included in the SELECT clause, separated by commas.
Parameters
columns The columns to select. If empty, all columns ("*") are selected.
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 82 of file QueryBuilder.java.
where()
QueryBuilder web.ambassador.db.QueryBuilder.where (String condition) inline
Adds a WHERE clause to the SQL query with the specified condition.
Parameters
condition The condition for the WHERE clause (e.g., "age > 25").
Returns
The current QueryBuilder instance to allow method chaining.
Definition at line 107 of file QueryBuilder.java.
The documentation for this class was generated from the following file:
src/web/ambassador/db/QueryBuilder.java